name: ocrmypdfgui # you probably want to 'snapcraft register <name>'
title: ocrmypdfgui
base: core20 # the base snap is the execution environment for this snap
version: '0.9.03' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow
description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like. Includes full current version of OCRmyPDF as backend. Icons and banner made by Freepik from www.flaticon.com
icon: gui/ocrmypdfgui.png
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures: [amd64]

environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata
    GS_LIB: $SNAP/usr/share/ghostscript/9.26/Resource/Init
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.26/Resource/Font
    #GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu
    #PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.8/site-packages
apps:
  ocrmypdfgui:
    command: python3 $SNAP/lib/python3.8/site-packages/ocrmypdfgui/__main__.py
    desktop: $SNAPCRAFT_PROJECT_DIR/gui/ocrmypdfgui.desktop
    extensions: [gnome-3-38]

    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media


parts:
  ocrmypdfgui:
    # See 'snapcraft plugins'
    plugin: python
    source: .
#    stage:
#      - -usr/lib/*/libpango*
    stage-packages: [ghostscript, icc-profiles-free, liblept5, libxml2, pngquant, tesseract-ocr-all, unpaper, qpdf, zlib1g]

    python-packages:
      - ocrmypdf
#      - cffi  # must be a setup and install requirement
#      - coloredlogs # strictly optional
#      - img2pdf  # pure Python, so track HEAD closely
#      - pdfminer.six
#      - pikepdf
#      - Pillow
#      - pluggy
#      - reportlab
#      - setuptools
#      - tqdm

#    override-build: |
#      snapcraftctl build
#      sed -i 's/find_library(libname)/"liblept.so.5"/g' $SNAPCRAFT_PART_INSTALL/lib/python3.8/site-packages/ocrmypdf/leptonica.py
