name: ocrmypdfgui
title: ocrmypdfgui
base: core20
version: '0.9.15' # Matched with setup.py
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow
description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like. Includes full current version of OCRmyPDF as backend. Icons and banner made by Freepik from www.flaticon.com
icon: gui/ocrmypdfgui.png
grade: stable
confinement: strict

architectures: [amd64]

environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata # Verify version from staged tesseract
    GS_LIB: $SNAP/usr/share/ghostscript/9.50/Resource/Init     # Verify version from staged ghostscript
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.50/Resource/Font # Verify version from staged ghostscript
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu

apps:
  ocrmypdfgui:
    command: usr/bin/ocrmypdfgui # Keeping this for now, diagnostics will guide if it's wrong
    desktop: gui/ocrmypdfgui.desktop
    extensions: [gnome-3-38] 
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media

parts:
  ocrmypdfgui:
    plugin: python
    source: .
    build-packages: 
      - python3-setuptools
      - python3-pip
      - python3-wheel
    python-packages:
      - cffi
      - coloredlogs
      - img2pdf
      - ocrmypdf
      - pdfminer.six
      - pikepdf
      - Pillow
      - pluggy
      - pytesseract
      - rarfile
      - reportlab
      - tqdm
    stage-packages:
      - ghostscript
      - tesseract-ocr-eng 
    override-build: |
      ln -sf ../usr/lib/libsnapcraft-preload.so $SNAPCRAFT_PART_INSTALL/lib/libsnapcraft-preload.so
      snapcraftctl build
    override-prime: |
      set -x # Enable verbose output for this script block
      snapcraftctl prime
      echo "--- Listing common bin directories in prime stage ---"
      echo "Listing $SNAPCRAFT_PRIME/usr/bin:"
      ls -la $SNAPCRAFT_PRIME/usr/bin || echo "Failed to list $SNAPCRAFT_PRIME/usr/bin"
      echo "Listing $SNAPCRAFT_PRIME/bin:"
      ls -la $SNAPCRAFT_PRIME/bin || echo "Failed to list $SNAPCRAFT_PRIME/bin"
      echo "Listing $SNAPCRAFT_PRIME/snap/bin:"
      ls -la $SNAPCRAFT_PRIME/snap/bin || echo "Failed to list $SNAPCRAFT_PRIME/snap/bin"
      
      echo "--- Searching for ocrmypdfgui and python3 in prime stage ---"
      echo "Finding ocrmypdfgui:"
      find $SNAPCRAFT_PRIME -name ocrmypdfgui -ls || echo "ocrmypdfgui not found"
      echo "Finding python3 related files/dirs (NO FOLLOW):"
      find $SNAPCRAFT_PRIME -name python3 -ls || echo "python3 not found (no symlink follow)"
      echo "Finding python3 related files/dirs (FOLLOW SYMLINKS in search path):"
      find -L $SNAPCRAFT_PRIME -name python3 -ls || echo "python3 not found (symlink follow in search)"
      echo "--- End of diagnostic lists ---"
