name: ocrmypdfgui
title: ocrmypdfgui
base: core20
version: '0.9.15' # Matched with setup.py
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow
description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like. Includes full current version of OCRmyPDF as backend. Icons and banner made by Freepik from www.flaticon.com
icon: gui/ocrmypdfgui.png
grade: stable
confinement: strict

architectures: [amd64]

environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata # Verify version from staged tesseract
    GS_LIB: $SNAP/usr/share/ghostscript/9.50/Resource/Init     # Verify version from staged ghostscript
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.50/Resource/Font # Verify version from staged ghostscript
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu

apps:
  ocrmypdfgui:
    command: usr/bin/ocrmypdfgui # This should now exist due to override-prime
    desktop: gui/ocrmypdfgui.desktop
    extensions: [gnome-3-38] 
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media

parts:
  ocrmypdfgui:
    plugin: python
    source: .
    build-packages: 
      - python3-setuptools
      - python3-pip
      - python3-wheel
    python-packages:
      - cffi
      - coloredlogs
      - img2pdf
      - ocrmypdf
      - pdfminer.six
      - pikepdf
      - Pillow
      - pluggy
      - pytesseract
      - rarfile
      - reportlab
      - tqdm
    stage-packages:
      - ghostscript
      - tesseract-ocr-eng 
    override-build: |
      ln -sf ../usr/lib/libsnapcraft-preload.so $SNAPCRAFT_PART_INSTALL/lib/libsnapcraft-preload.so
      snapcraftctl build
    override-prime: |
      set -x 
      # Run default prime actions first.
      snapcraftctl prime
      
      echo "--- Manually staging ocrmypdfgui script from part's build artifacts ---"
      # $SNAPCRAFT_PART_DIR points to the current part's directory in parts/
      # The venv was created in $SNAPCRAFT_PART_DIR/install during the build step of the part.
      SOURCE_SCRIPT="$SNAPCRAFT_PART_DIR/install/bin/ocrmypdfgui"
      
      DEST_DIR="$SNAPCRAFT_PRIME/usr/bin"
      DEST_SCRIPT_PATH="$DEST_DIR/ocrmypdfgui"
      
      if [ -f "$SOURCE_SCRIPT" ]; then
        echo "Found script at $SOURCE_SCRIPT"
        mkdir -p "$DEST_DIR"
        echo "Copying $SOURCE_SCRIPT to $DEST_SCRIPT_PATH"
        cp "$SOURCE_SCRIPT" "$DEST_SCRIPT_PATH"
        chmod +x "$DEST_SCRIPT_PATH"
        echo "Copied ocrmypdfgui to $DEST_SCRIPT_PATH and made executable."
      else
        echo "ERROR: ocrmypdfgui script not found at $SOURCE_SCRIPT. This is unexpected."
      fi

      echo "--- Final check for ocrmypdfgui in prime/usr/bin ---"
      ls -la "$DEST_SCRIPT_PATH" || echo "ocrmypdfgui still not in $DEST_SCRIPT_PATH after manual copy."
      echo "--- Listing $SNAPCRAFT_PRIME/usr/bin (after attempting copy) ---"
      ls -la $SNAPCRAFT_PRIME/usr/bin || true
      echo "--- End of override-prime for ocrmypdfgui part ---"
