name: ocrmypdfgui
base: core24
version: '1.0.1'
title: ocrmypdfgui
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow

description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like. Includes full current version of OCRmyPDF as backend. Icons and banner made by Freepik from www.flaticon.com
icon: gui/ocrmypdfgui.png

grade: stable
confinement: strict

apps:
  ocrmypdfgui:
    command: bin/desktop-launch $SNAP/usr/bin/ocrmypdfgui
    desktop: gui/ocrmypdfgui.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media

parts:
  ocrmypdfgui:
    plugin: python
    source: .
    build-packages:
      - python3-setuptools
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - python3-pip
      - python3-wheel
      - libqpdf-dev
      - g++
      - pkg-config
      - qtbase5-dev
      - qt5-qmake
      - qtchooser
      - qtbase5-dev-tools
      - qttools5-dev-tools
      - libqt5svg5-dev
      - libglib2.0-bin
      - libglib2.0-dev
      - libsm6
      - libxrender1
      - libxext6
      - libjpeg-dev
      - zlib1g-dev
      - libtiff-dev
      - libopenjp2-7-dev
      - libpng-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - libharfbuzz-dev
      - libfribidi-dev
      - libxcb1-dev
      - libxkbcommon-x11-0
      - findutils
    python-packages: []
    stage-packages:
      - ghostscript
      - tesseract-ocr-all
      - libproxy1v5
      - libqpdf29
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - qt5-gtk-platformtheme
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xfixes0
      - libxcb-shape0
      - libxcb-randr0
      - libxcb-xkb1
      - libxkbcommon-x11-0
      - libsm6
      - libxrender1
      - libxext6
      - libjpeg8
      - zlib1g
      - libtiff5
      - libopenjp2-7
      - libpng16-16
      - libfreetype6
      - liblcms2-2
      - libwebp6
      - libharfbuzz0b
      - libfribidi0
    override-build: |
      set -x
      snapcraftctl build
      # Ensure the PyQt5 platform plugins are staged
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/platforms
      cp -r $(find /usr/lib -name "libqxcb.so" | head -n1) $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/platforms/ || true
      # Copy .desktop and icon
      mkdir -p $SNAPCRAFT_PART_INSTALL/gui
      cp gui/ocrmypdfgui.desktop $SNAPCRAFT_PART_INSTALL/gui/
      cp gui/ocrmypdfgui.png $SNAPCRAFT_PART_INSTALL/gui/
      # Ensure main entry is in /usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp $(find $SNAPCRAFT_PART_INSTALL -name ocrmypdfgui | head -n1) $SNAPCRAFT_PART_INSTALL/usr/bin/ocrmypdfgui || true
    override-prime: |
      set -x
      snapcraftctl prime
      # Copy .desktop and icon to prime
      mkdir -p $SNAPCRAFT_PRIME/gui
      cp gui/ocrmypdfgui.desktop $SNAPCRAFT_PRIME/gui/
      cp gui/ocrmypdfgui.png $SNAPCRAFT_PRIME/gui/
      # Ensure /usr/bin/ocrmypdfgui is present
      mkdir -p $SNAPCRAFT_PRIME/usr/bin
      cp $(find $SNAPCRAFT_PRIME -name ocrmypdfgui | head -n1) $SNAPCRAFT_PRIME/usr/bin/ocrmypdfgui || true
