name: ocrmypdfgui # you probably want to 'snapcraft register <name>'
title: ocrmypdfgui
base: core20 # the base snap is the execution environment for this snap
version: '0.9.15' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow
description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like. Includes full current version of OCRmyPDF as backend. Icons and banner made by Freepik from www.flaticon.com
icon: gui/ocrmypdfgui.png
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
#
architectures: [amd64]

environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata
    GS_LIB: $SNAP/usr/share/ghostscript/9.50/Resource/Init
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.50/Resource/Font
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu

apps:
  ocrmypdfgui:
    command: python3 -m ocrmypdfgui
    desktop: $SNAPCRAFT_PROJECT_DIR/gui/ocrmypdfgui.desktop
    extensions: [gnome-3-38]

    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media


parts:
  ocrmypdfgui:
    # See 'snapcraft plugins'
    plugin: python
    source: .

    python-packages:
      - cffi # >= 1.9.1
      - coloredlogs # >= 14.0
      - img2pdf # >= 0.3.0, < 0.5
      - ocrmypdf # >= 12.0.2
      - pdfminer.six # >= 20191110, != 20200720, <= 20201018
      - pikepdf # >= 2.10.0
      - Pillow # >= 8.1.2
      - pluggy # >= 0.13.0, < 1.0
      - PyGObject
      - pytesseract # >= 0.3.8
      - rarfile # >= 3.0
      - reportlab # >= 3.5.66
      - setuptools
      - tqdm # >= 4

    stage-packages:
      - ghostscript
      - tesseract-ocr-eng

    override-build: |
      ln -sf ../usr/lib/libsnapcraft-preload.so $SNAPCRAFT_PART_INSTALL/lib/libsnapcraft-preload.so
      snapcraftctl build

