name: ocrmypdfgui
title: ocrmypdfgui
base: core20
version: '0.9.15' # Matched with setup.py
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow
description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like. Includes full current version of OCRmyPDF as backend. Icons and banner made by Freepik from www.flaticon.com
icon: gui/ocrmypdfgui.png # Expects prime/gui/ocrmypdfgui.png
grade: stable
confinement: strict

architectures: [amd64]

environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata # Verify version from staged tesseract
    GS_LIB: $SNAP/usr/share/ghostscript/9.50/Resource/Init     # Verify version from staged ghostscript
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.50/Resource/Font # Verify version from staged ghostscript
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu

apps:
  ocrmypdfgui:
    command: usr/bin/ocrmypdfgui 
    desktop: gui/ocrmypdfgui.desktop # Expects prime/gui/ocrmypdfgui.desktop
    extensions: [gnome-3-38] 
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media

parts:
  ocrmypdfgui:
    plugin: python
    source: . # This includes the 'gui' directory
    build-packages: 
      - python3-setuptools
      - python3-pip
      - python3-wheel
      - findutils # Added for the find command in override-build
    python-packages:
      - cffi
      - coloredlogs
      - img2pdf
      - ocrmypdf
      - pdfminer.six
      - pikepdf
      - Pillow
      - pluggy
      - pytesseract
      - rarfile
      - reportlab
      - tqdm
    stage-packages:
      - ghostscript
      - tesseract-ocr-eng 
    override-build: |
      set -x
      echo "## Starting override-build for ocrmypdfgui part ##"
      snapcraftctl build
      
      echo "--- Locating ocrmypdfgui script within $SNAPCRAFT_PART_INSTALL ---"
      SCRIPT_IN_VENV_BIN="$SNAPCRAFT_PART_INSTALL/bin/ocrmypdfgui"
      FOUND_SCRIPT_PATH=""

      if [ -f "$SCRIPT_IN_VENV_BIN" ]; then
        echo "Script found at standard venv path: $SCRIPT_IN_VENV_BIN"
        FOUND_SCRIPT_PATH="$SCRIPT_IN_VENV_BIN"
      else
        echo "Script NOT in $SCRIPT_IN_VENV_BIN. Searching elsewhere in $SNAPCRAFT_PART_INSTALL..."
        # Ensure find exits 0 even if not found, to not stop the script with set -e (if it were set)
        FOUND_SCRIPT_PATH=$(find "$SNAPCRAFT_PART_INSTALL" -name ocrmypdfgui -type f -print -quit 2>/dev/null) || true
        if [ -n "$FOUND_SCRIPT_PATH" ]; then
          echo "Script found at non-standard path: $FOUND_SCRIPT_PATH"
        else
          echo "ERROR: ocrmypdfgui script NOT FOUND anywhere within $SNAPCRAFT_PART_INSTALL after 'snapcraftctl build'."
          echo "Listing contents of $SNAPCRAFT_PART_INSTALL/bin/ for debugging:"
          ls -la "$SNAPCRAFT_PART_INSTALL/bin/" || true
        fi
      fi
      
      if [ -n "$FOUND_SCRIPT_PATH" ]; then
        echo "--- Staging found ocrmypdfgui script to $SNAPCRAFT_PART_INSTALL/usr/bin/ ---"
        DEST_BIN_IN_PART_INSTALL="$SNAPCRAFT_PART_INSTALL/usr/bin"
        mkdir -p "$DEST_BIN_IN_PART_INSTALL"
        cp "$FOUND_SCRIPT_PATH" "$DEST_BIN_IN_PART_INSTALL/ocrmypdfgui"
        chmod +x "$DEST_BIN_IN_PART_INSTALL/ocrmypdfgui"
        echo "Copied $FOUND_SCRIPT_PATH to $DEST_BIN_IN_PART_INSTALL/ocrmypdfgui."
      else
        echo "WARNING: No ocrmypdfgui script found to stage into part's /usr/bin."
      fi
      echo "## End of override-build for ocrmypdfgui part ##"

    override-prime: |
      set -x 
      snapcraftctl prime 
      
      echo "--- Manually staging .desktop file and icon for priming ---"
      # $SNAPCRAFT_PART_SRC should point to the source files of the part within the build.
      ASSETS_SOURCE_DIR="$SNAPCRAFT_PART_SRC/gui" 
      DEST_GUI_DIR_IN_PRIME="$SNAPCRAFT_PRIME/gui"
      
      mkdir -p "$DEST_GUI_DIR_IN_PRIME"
      
      if [ -d "$ASSETS_SOURCE_DIR" ]; then
        if [ -f "$ASSETS_SOURCE_DIR/ocrmypdfgui.desktop" ]; then
          cp "$ASSETS_SOURCE_DIR/ocrmypdfgui.desktop" "$DEST_GUI_DIR_IN_PRIME/"
          echo "Copied ocrmypdfgui.desktop to $DEST_GUI_DIR_IN_PRIME/"
        else
          echo "ERROR from override-prime: $ASSETS_SOURCE_DIR/ocrmypdfgui.desktop not found."
        fi
        
        if [ -f "$ASSETS_SOURCE_DIR/ocrmypdfgui.png" ]; then
          cp "$ASSETS_SOURCE_DIR/ocrmypdfgui.png" "$DEST_GUI_DIR_IN_PRIME/"
          echo "Copied ocrmypdfgui.png to $DEST_GUI_DIR_IN_PRIME/"
        else
          echo "ERROR from override-prime: $ASSETS_SOURCE_DIR/ocrmypdfgui.png not found."
        fi
      else
        echo "ERROR from override-prime: Assets source directory $ASSETS_SOURCE_DIR not found."
      fi

      echo "--- Listing $DEST_GUI_DIR_IN_PRIME (for .desktop and .icon) ---"
      ls -la "$DEST_GUI_DIR_IN_PRIME" || true
      echo "--- Listing $SNAPCRAFT_PRIME/usr/bin (for command) ---"
      ls -la $SNAPCRAFT_PRIME/usr/bin || true
      echo "--- End of override-prime for ocrmypdfgui part ---"
