name: ocrmypdfgui # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hobby Project GUI for the Python Program "OCRmyPDF" by James R. Barlow
description: |
  I use James R. Barlow's OCRmyPDF heavily in my paperless Office and have created this Python Project as a GUI wrapper to run batch jobs on my filesystem. This is strictly a Hobby Project and is not "official". Feel free to use it if you like.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]

parts:
   # https://forum.snapcraft.io/t/the-debian-multiarch-triplet-provider-launch-stage-snap/11738
  debian-multiarch-triplet-provider-launch:
    plugin: nil
    stage-snaps:
    - debian-multiarch-triplet-provider-launch

  # https://forum.snapcraft.io/t/the-tcltk-launch-stage-snap/11740
  tcltk-launch:
    plugin: nil
    stage-snaps:
    - tcltk-launch


  ocrmypdfgui:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    stage-packages:
      - ocrmypdf
      - tcl
      - python3.8-tk
      - python3-pil.imagetk
      - fontconfig-config
      - fonts-dejavu-core
      - fonts-dejavu-extra
      - locales-all
      - ghostscript
      - icc-profiles-free
      - liblept5
      - libxml2
      - pngquant
      - tesseract-ocr
      - zlib1g

    python-packages:
      - ocrmypdf
      - cffi  # must be a setup and install requirement
      - coloredlogs # strictly optional
      - img2pdf  # pure Python, so track HEAD closely
      - pdfminer.six
      - pikepdf
      - Pillow
      - pluggy
      - reportlab
      - setuptools
      - tqdm

apps:
  ocrmypdfgui:
    command: bin/ocrmypdfgui
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/python3.8
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/
      TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
    adapter: full
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7
      - wayland
      - x11
      - home
      - removable-media
      - network
      - network-bind

    command-chain:
    - bin/debian-multiarch-triplet-provider-launch
    - bin/tcltk-launch
